version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - "${APP_NETWORK}"
    volumes:
      - ./dist:/var/www/html
      - ./nginx-logs:/var/log/nginx
      - ./infrastructure/docker/nginx/conf.d:/etc/nginx/conf.d
      - ./infrastructure/docker/nginx/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=${APP_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - VIRTUAL_PORT=${NGINX_PORT}
      - VIRTUAL_HOST=${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: "${APP_NETWORK}"
